/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.ChiTietCH;
import NHOM_08.nhom_08;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/*
 * @author LE TRAN TIEN
 */
public class CuaHang extends javax.swing.JFrame {

	/**
	 * Creates new form CuaHang
	 */
	public CuaHang() {
		initComponents();
		this.setTitle("Cửa hàng văn phòng phẩm");
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jpl_muahang = new javax.swing.JPanel();
                jScrollPane15 = new javax.swing.JScrollPane();
                tblSanPham1 = new javax.swing.JTable();
                jPanel26 = new javax.swing.JPanel();
                lblMaSanPham_SanPham1 = new javax.swing.JLabel();
                lblTenSanPham_SanPham1 = new javax.swing.JLabel();
                txtMaKhachCH = new javax.swing.JTextField();
                jLabel34 = new javax.swing.JLabel();
                lblTonKho_SanPham1 = new javax.swing.JLabel();
                jLabel35 = new javax.swing.JLabel();
                cbbHangSanXuat_SanPham1 = new javax.swing.JComboBox<>();
                txtTonKho_SanPham1 = new javax.swing.JTextField();
                jScrollPane16 = new javax.swing.JScrollPane();
                txtChuThich_SanPham1 = new javax.swing.JTextArea();
                txtTenSanPham_SanPham2 = new javax.swing.JTextField();
                jScrollPane17 = new javax.swing.JScrollPane();
                spMuaCH = new javax.swing.JTable();
                jPanel28 = new javax.swing.JPanel();
                jButton3 = new javax.swing.JButton();
                btXoaCH = new javax.swing.JButton();
                jLabel36 = new javax.swing.JLabel();
                vatTF = new javax.swing.JTextField();
                jLabel37 = new javax.swing.JLabel();
                jLabel38 = new javax.swing.JLabel();
                tongCongTF = new javax.swing.JLabel();
                btcong = new javax.swing.JButton();
                bttru = new javax.swing.JButton();
                thanhTienTF = new javax.swing.JLabel();
                tienKhachTraTF = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                tienThuaTF = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();
                btDangXuat = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                addComponentListener(new java.awt.event.ComponentAdapter() {
                        public void componentShown(java.awt.event.ComponentEvent evt) {
                                formComponentShown(evt);
                        }
                });

                jpl_muahang.addComponentListener(new java.awt.event.ComponentAdapter() {
                        public void componentShown(java.awt.event.ComponentEvent evt) {
                                jpl_muahangComponentShown(evt);
                        }
                });

                tblSanPham1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null, null, null},
                                {null, null, null, null, null, null, null, null, null}
                        },
                        new String [] {
                                "Mã Sản Phẩm ", "Tên Sản Phẩm", "Loại Sản Phẩm", "Giá Nhập", "Giá Bán", "Nhà Sản Xuất", "Tồn Kho", "ảnh", "Chú Thích"
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                false, true, true, true, true, true, true, true, true
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                tblSanPham1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tblSanPham1MouseClicked(evt);
                        }
                });
                tblSanPham1.addComponentListener(new java.awt.event.ComponentAdapter() {
                        public void componentShown(java.awt.event.ComponentEvent evt) {
                                tblSanPham1ComponentShown(evt);
                        }
                });
                jScrollPane15.setViewportView(tblSanPham1);

                jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin khách hàng"));

                lblMaSanPham_SanPham1.setText("Tên Khách Hàng");

                lblTenSanPham_SanPham1.setText("Địa chỉ");

                jLabel34.setText("Giới tính");

                lblTonKho_SanPham1.setText("Số điện thoại");

                jLabel35.setText("Chú Thích");

                cbbHangSanXuat_SanPham1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam ", "Nữ" }));
                cbbHangSanXuat_SanPham1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cbbHangSanXuat_SanPham1ActionPerformed(evt);
                        }
                });

                txtChuThich_SanPham1.setColumns(20);
                txtChuThich_SanPham1.setRows(5);
                jScrollPane16.setViewportView(txtChuThich_SanPham1);

                javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
                jPanel26.setLayout(jPanel26Layout);
                jPanel26Layout.setHorizontalGroup(
                        jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel26Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTenSanPham_SanPham1)
                                        .addComponent(lblMaSanPham_SanPham1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel26Layout.createSequentialGroup()
                                                .addComponent(txtMaKhachCH, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblTonKho_SanPham1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel34))
                                                .addGap(30, 30, 30)
                                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(cbbHangSanXuat_SanPham1, 0, 169, Short.MAX_VALUE)
                                                        .addComponent(txtTonKho_SanPham1)))
                                        .addComponent(jScrollPane16))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel26Layout.createSequentialGroup()
                                        .addGap(137, 137, 137)
                                        .addComponent(txtTenSanPham_SanPham2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(322, Short.MAX_VALUE)))
                );
                jPanel26Layout.setVerticalGroup(
                        jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel26Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel26Layout.createSequentialGroup()
                                                .addComponent(jLabel34)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblTonKho_SanPham1))
                                        .addGroup(jPanel26Layout.createSequentialGroup()
                                                .addComponent(cbbHangSanXuat_SanPham1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(txtTonKho_SanPham1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel26Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblMaSanPham_SanPham1)
                                        .addComponent(txtMaKhachCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblTenSanPham_SanPham1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel35))
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                                        .addContainerGap(47, Short.MAX_VALUE)
                                        .addComponent(txtTenSanPham_SanPham2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)))
                );

                spMuaCH.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Tên Sản Phẩm", "Số Lượng", "Giá", "Thành Tiền"
                        }
                ));
                spMuaCH.addAncestorListener(new javax.swing.event.AncestorListener() {
                        public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                                spMuaCHAncestorAdded(evt);
                        }
                        public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                        }
                        public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                        }
                });
                spMuaCH.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                spMuaCHMouseClicked(evt);
                        }
                });
                spMuaCH.addComponentListener(new java.awt.event.ComponentAdapter() {
                        public void componentShown(java.awt.event.ComponentEvent evt) {
                                spMuaCHComponentShown(evt);
                        }
                });
                jScrollPane17.setViewportView(spMuaCH);

                jPanel28.setBorder(javax.swing.BorderFactory.createTitledBorder("Lựa chọn"));

                jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jButton3.setText("Thanh Toán");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });

                btXoaCH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btXoaCH.setText("Xóa");
                btXoaCH.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btXoaCHActionPerformed(evt);
                        }
                });

                jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel36.setText("Tổng tiền:");

                vatTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                vatTF.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                vatTFActionPerformed(evt);
                        }
                });
                vatTF.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                vatTFKeyPressed(evt);
                        }
                });

                jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel37.setText("VAT:");

                jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel38.setText("Thành Tiền");

                tongCongTF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                tongCongTF.setText("0");

                btcong.setText("+");
                btcong.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btcongActionPerformed(evt);
                        }
                });

                bttru.setText("-");
                bttru.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bttruActionPerformed(evt);
                        }
                });

                thanhTienTF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                thanhTienTF.setText("0");

                tienKhachTraTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                tienKhachTraTF.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                tienKhachTraTFKeyPressed(evt);
                        }
                });

                jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel6.setText("Tiền khách trả:");

                tienThuaTF.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                tienThuaTF.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tienThuaTFActionPerformed(evt);
                        }
                });

                jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                jLabel7.setText("Tiền thừa");

                jButton1.setText("jButton1");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
                jPanel28.setLayout(jPanel28Layout);
                jPanel28Layout.setHorizontalGroup(
                        jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel28Layout.createSequentialGroup()
                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel28Layout.createSequentialGroup()
                                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel28Layout.createSequentialGroup()
                                                                .addGap(40, 40, 40)
                                                                .addComponent(btcong, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(bttru, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel28Layout.createSequentialGroup()
                                                                .addGap(52, 52, 52)
                                                                .addComponent(jButton1)))
                                                .addGap(106, 106, 106)
                                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(44, 44, 44)
                                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(thanhTienTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(vatTF)
                                                        .addComponent(tongCongTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel28Layout.createSequentialGroup()
                                                                .addGap(245, 245, 245)
                                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel28Layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(btXoaCH, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(tienKhachTraTF)
                                                        .addComponent(tienThuaTF))))
                                .addContainerGap())
                );
                jPanel28Layout.setVerticalGroup(
                        jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel28Layout.createSequentialGroup()
                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel36)
                                        .addComponent(tongCongTF))
                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel28Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel37)
                                                        .addComponent(vatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(bttru, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btcong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(thanhTienTF)))
                                        .addGroup(jPanel28Layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addComponent(jButton1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tienKhachTraTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tienThuaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton3)
                                        .addComponent(btXoaCH))
                                .addContainerGap(30, Short.MAX_VALUE))
                );

                btDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                btDangXuat.setText("Đăng Xuất");
                btDangXuat.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btDangXuatActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jpl_muahangLayout = new javax.swing.GroupLayout(jpl_muahang);
                jpl_muahang.setLayout(jpl_muahangLayout);
                jpl_muahangLayout.setHorizontalGroup(
                        jpl_muahangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpl_muahangLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jpl_muahangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane17)
                                        .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jpl_muahangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jpl_muahangLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())
                                        .addGroup(jpl_muahangLayout.createSequentialGroup()
                                                .addGap(227, 227, 227)
                                                .addComponent(btDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                );
                jpl_muahangLayout.setVerticalGroup(
                        jpl_muahangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpl_muahangLayout.createSequentialGroup()
                                .addGroup(jpl_muahangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jpl_muahangLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jpl_muahangLayout.createSequentialGroup()
                                                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 13, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1289, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jpl_muahang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 630, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jpl_muahang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void tblSanPham1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPham1MouseClicked

	    int viTriDongVuaBam = tblSanPham1.getSelectedRow();
	    //int row = spMuaCH.getSelectedRow();
	    String MaSP = tblSanPham1.getValueAt(tblSanPham1.getSelectedRow(), 0).toString();
	    // TODO add your handling code here:
    }//GEN-LAST:event_tblSanPham1MouseClicked

    private void cbbHangSanXuat_SanPham1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbHangSanXuat_SanPham1ActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_cbbHangSanXuat_SanPham1ActionPerformed

    private void vatTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vatTFActionPerformed

	    // TODO add your handling code here:
    }//GEN-LAST:event_vatTFActionPerformed

    private void vatTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vatTFKeyPressed
	    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
		    setThanhTien();
	    }

    }//GEN-LAST:event_vatTFKeyPressed

    private void btcongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcongActionPerformed
	    int row = spMuaCH.getSelectedRow();
	    int row1 = tblSanPham1.getSelectedRow();
	    if (row != -1) {
		    int sl = (int) spMuaCH.getValueAt(row, 1);
		    int tk = (int) tblSanPham1.getValueAt(row1, 5);
		    if (sl < tk) {
			    spMuaCH.setValueAt(sl + 1, row, 1);
			    setTongCong();
			    setThanhTien();
			    setThanhTienChiTiet();
		    } else {
			    JOptionPane.showMessageDialog(this, "Số lượng chọn lớn hơn sản phẩm hiện có!");
		    }
	    } else {
		    JOptionPane.showMessageDialog(this, "Bạn chưa chọn Sản Phẩm!");
	    }
	    // TODO add your handling code here:
    }//GEN-LAST:event_btcongActionPerformed

    private void bttruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttruActionPerformed
	    int row = spMuaCH.getSelectedRow();
	    if (row != -1) {
		    int sl = (int) spMuaCH.getValueAt(row, 1);
		    if (sl > 1) {
			    spMuaCH.setValueAt(sl - 1, row, 1);
			    setTongCong();
			    setThanhTien();
			    setThanhTienChiTiet();
		    } else {
			    JOptionPane.showMessageDialog(this, "Số lượng đang là 1!");
		    }
	    } else
		    JOptionPane.showMessageDialog(this, "Bạn chưa chọn sản phẩm!");        // TODO add your handling code here:
    }//GEN-LAST:event_bttruActionPerformed

    private void tblSanPham1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblSanPham1ComponentShown
	    // TODO add your handling code here:
    }//GEN-LAST:event_tblSanPham1ComponentShown

    private void jpl_muahangComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpl_muahangComponentShown

	    // TODO add your handling code here:
    }//GEN-LAST:event_jpl_muahangComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
	    LayDuLieuSanPhamCH("1");
	    //layDuLieuCuahang("1");
	    // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void tienKhachTraTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tienKhachTraTFKeyPressed
	    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
		    int tienThua, tKhachTra;
		    try {
			    tKhachTra = Integer.parseInt(tienKhachTraTF.getText());
		    } catch (Exception e) {
			    tKhachTra = 0;
			    System.out.println(e);
		    }
		    if (tKhachTra > thanhTien) {
			    tienThua = (int) (tKhachTra - thanhTien);
			    tienThuaTF.setText(String.valueOf(tienThua));
		    } else {
			    JOptionPane.showMessageDialog(this, "Tiền khách trả phải lớn hơn hặc bằng thành tiền!");
		    }
	    }
    }//GEN-LAST:event_tienKhachTraTFKeyPressed

    private void btXoaCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaCHActionPerformed

	    // TODO add your handling code here:
    }//GEN-LAST:event_btXoaCHActionPerformed

    private void btDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangXuatActionPerformed
	    // TODO add your handling code here:
	    DangNhap dangNhap = new DangNhap();
	    dangNhap.show();
	    this.setVisible(false);

    }//GEN-LAST:event_btDangXuatActionPerformed

    private void tienThuaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tienThuaTFActionPerformed
	    // TODO add your handling code here:
    }//GEN-LAST:event_tienThuaTFActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
	    int row = spMuaCH.getSelectedRow();
	    int row1 = tblSanPham1.getSelectedRow();
	    String cautruyvan = "";
	    cautruyvan = "insert into ChiTietHoaDon(MaHoaDon, MaSanPham, SoLuong, TongTien, GhiChu) values(" + tblSanPham1.getValueAt(row1, 0) + "," + tblSanPham1.getValueAt(row1, 0) + "," + spMuaCH.getValueAt(row, 1) + "," + spMuaCH.getValueAt(row, 2) + ",N'" + "" + "')";
	    nhom_08.connection.ExcuteQueryUpdateDB(cautruyvan);
	    int sl = (int) spMuaCH.getValueAt(row, 1);
	    int tk = (int) tblSanPham1.getValueAt(row1, 5);
	    if (tk < sl) {
		    JOptionPane.showMessageDialog(this, "Sản phẩm hết hàng ");
	    } else {
		    if (tienKhachTraTF.getText().equals("") || txtMaKhachCH.getText().equals("")) {
			    JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ!");
		    } else {

			    cautruyvan = "update ChiTietHoaDon set SoLuong = " + spMuaCH.getValueAt(row, 1) + "where MaSanPham=" + tblSanPham1.getValueAt(row1, 0) + "";
			    //cautruyvan = "select SanPham.TenSanPham,TonKho,GiaBan from SanPham where  TrangThai=" + TrangThai;
			    ResultSet rs = nhom_08.connection.ExcuteQueryGetTable(cautruyvan);
			    JOptionPane.showMessageDialog(this, "Thanh toán thành công");
			    tongCongTF.setText("0");
			    vatTF.setText("");
			    thanhTienTF.setText("0");
			    tienKhachTraTF.setText("");
			    tienKhachTraTF.requestFocus();
			    tienThuaTF.setText("");
		    }
		    LayDuLieuSanPhamCH("1");
	    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void spMuaCHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spMuaCHMouseClicked
	    setTongCong();
	    setThanhTien();
	    setThanhTienChiTiet();
	    // TODO add your handling code here:
    }//GEN-LAST:event_spMuaCHMouseClicked

    private void spMuaCHAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spMuaCHAncestorAdded

	    // TODO add your handling code here:
    }//GEN-LAST:event_spMuaCHAncestorAdded

    private void spMuaCHComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_spMuaCHComponentShown

	    // TODO add your handling code here:
    }//GEN-LAST:event_spMuaCHComponentShown

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButton1ActionPerformed
//Bán Hàng  
	private DefaultTableModel tableModel;
	private long tongCong, thanhTien;
	private String mahd;

	public void actionPerformed(ActionEvent event) {
//        String maKT;
//        String ma = event.getActionCommand();
//        maKT = ma.substring(0, 2);
//        if("CF".equals(maKT) && mahd.equals("00000")){
//            int ck, v;
//            int row = spMuaCH.getRowCount();
//            int kt = 0;
//            for(int i = 0; i < row; i++)
//            setTongCong();
//            setThanhTien();
//        }
	}

	public void setTongCong() {
		tongCong = 0;
		int row = spMuaCH.getSelectedRow();
		tongCong += Integer.parseInt(String.valueOf(spMuaCH.getValueAt(row, 3)));
		tongCongTF.setText(String.valueOf(tongCong));

	}

	public void setThanhTien() {
		int v;
		try {
			if ("".equals(vatTF.getText())) {
				v = 0;
			} else {
				v = Integer.parseInt(vatTF.getText());
			}
		} catch (Exception ex) {
			v = 0;
			System.out.println(ex);
		}
		thanhTien = tongCong * (100 + v) / 100;
		thanhTienTF.setText(String.valueOf(thanhTien));
	}

	public void setThanhTienChiTiet() {
		int row = spMuaCH.getSelectedRow();
		int sl = (int) spMuaCH.getValueAt(row, 1);
		int dg = (int) spMuaCH.getValueAt(row, 2);
		spMuaCH.setValueAt(sl * dg, row, 3);
	}
	private long thanhTienn;

	public long getThanhTienn() {
		return thanhTienn;
	}

	public void layDuLieuCuahangCT(String TrangThai) {
		String cautruyvan = "";
		int row = spMuaCH.getSelectedRow();
		int row1 = tblSanPham1.getSelectedRow();
		String wheretk = tblSanPham1.getValueAt(row1, 0).toString();
		cautruyvan = "select SanPham.TenSanPham,GiaBan from SanPham where trangthai=1 and masanpham=" + wheretk;
		//cautruyvan = "select SanPham.TenSanPham,TonKho,GiaBan from SanPham where  TrangThai=" + TrangThai;
		//if(spMuaCH.getValueAt(row, 1)=tblSanPham1.getValueAt(row1, 1) );
//      cautruyvan = "select SanPham.TenSanPham, GiaBan,TonKho" 
//                + "SanPham.LoaiSanPham=LoaiSanPham.MaLoaiSanPham and SanPham.HangSanXuat=HangSanXuat.MaHangSanXuat and TrangThai=" + TrangThai; 
		ResultSet rs = nhom_08.connection.ExcuteQueryGetTable(cautruyvan);

		Object[] obj = new Object[]{"Tên Sản Phẩm", "Số Lượng", "Giá", "Thành Tiền"};
		DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
		spMuaCH.setModel(tableModel);
		int c = 0;
		try {
			while (rs.next()) {
				c++;
				Object[] item = new Object[4];
				item[0] = rs.getString("TenSanPham");
				item[1] = 1;
				item[2] = rs.getInt("GiaBan");
				item[3] = getThanhTienn();
				tableModel.addRow(item);
			}

		} catch (SQLException ex) {
			System.out.println(ex.toString());
		}
	
	}

	public void setDataCTCH(List<ChiTietCH> cthdList) {
		tableModel.setRowCount(0);
		for (ChiTietCH cthd : cthdList) {
			tableModel.addRow(new Object[]{
				cthd.getTenSanPham(),
				cthd.getSoLuong(),
				cthd.getDonGia(),
				cthd.getThanhTienn()
			});
		}
	}

	public void LayDuLieuSanPhamCH(String TrangThai) {
		String cautruyvan = "";
		cautruyvan = "select MaSanPham,SanPham.TenSanPham,SanPham.LoaiSanPham,GiaBan,HangsanXuat.TenHangSanXuat as THSX,TonKho,LoaiSanPham.TenLoaiSanPham"
			+ " as TenLoaiSanPham,Image from SanPham,LoaiSanPham,HangSanXuat where "
			+ "SanPham.LoaiSanPham=LoaiSanPham.MaLoaiSanPham and SanPham.HangSanXuat=HangSanXuat.MaHangSanXuat and TrangThai=" + TrangThai;
		ResultSet rs = nhom_08.connection.ExcuteQueryGetTable(cautruyvan);
		Object[] obj = new Object[]{"Mã Sản Phẩm", "Tên sản phẩm", "Loại sản phẩm", "Giá bán", "Hãng sản Xuất", "Số Lượng"};
		DefaultTableModel tableModel = new DefaultTableModel(obj, 0) {
			@Override
			public boolean isCellEditable(int row, int column) {
				return false;
			}
		};
		tblSanPham1.setModel(tableModel);
		int c = 0;
		try {
			while (rs.next()) {
				c++;
				Object[] item = new Object[8];
				item[0] = rs.getInt("MaSanPham");
				item[1] = rs.getString("TenSanPham");
				item[2] = rs.getString("TenLoaiSanPham");
				item[3] = rs.getInt("GiaBan");
				item[4] = rs.getString("THSX");
				item[5] = rs.getInt("TonKho");
				ListSelectionModel lsm = tblSanPham1.getSelectionModel();
				lsm.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
				lsm.addListSelectionListener(new ListSelectionListener() {
					@Override
					public void valueChanged(ListSelectionEvent e) {
						int row = tblSanPham1.getSelectedRow();
						if (row == -1) {
							return;
						}
						String mhd = (String) tblSanPham1.getValueAt(row, 1);
						//setThonTinHD(row, mhd);
						//setDataCTHD(ctdhdao.getChiTietDonHang(mhd));
						layDuLieuCuahangCT("1");
					}
				});
				tableModel.addRow(item);
			}
		} catch (SQLException ex) {
			System.out.println(ex.toString());
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CuaHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CuaHang().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btDangXuat;
        private javax.swing.JButton btXoaCH;
        private javax.swing.JButton btcong;
        private javax.swing.JButton bttru;
        private javax.swing.JComboBox<String> cbbHangSanXuat_SanPham1;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton3;
        private javax.swing.JLabel jLabel34;
        private javax.swing.JLabel jLabel35;
        private javax.swing.JLabel jLabel36;
        private javax.swing.JLabel jLabel37;
        private javax.swing.JLabel jLabel38;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel26;
        private javax.swing.JPanel jPanel28;
        private javax.swing.JScrollPane jScrollPane15;
        private javax.swing.JScrollPane jScrollPane16;
        private javax.swing.JScrollPane jScrollPane17;
        private javax.swing.JPanel jpl_muahang;
        private javax.swing.JLabel lblMaSanPham_SanPham1;
        private javax.swing.JLabel lblTenSanPham_SanPham1;
        private javax.swing.JLabel lblTonKho_SanPham1;
        private javax.swing.JTable spMuaCH;
        private javax.swing.JTable tblSanPham1;
        private javax.swing.JLabel thanhTienTF;
        private javax.swing.JTextField tienKhachTraTF;
        private javax.swing.JTextField tienThuaTF;
        private javax.swing.JLabel tongCongTF;
        private javax.swing.JTextArea txtChuThich_SanPham1;
        private javax.swing.JTextField txtMaKhachCH;
        private javax.swing.JTextField txtTenSanPham_SanPham2;
        private javax.swing.JTextField txtTonKho_SanPham1;
        private javax.swing.JTextField vatTF;
        // End of variables declaration//GEN-END:variables
}
