/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NHOM_08.nhom_08;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows 10 Version 2
 */
public class DangKy extends javax.swing.JFrame {

	/**
	 * Creates new form frmRegister
	 */
	public DangKy() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jRadioButton1 = new javax.swing.JRadioButton();
                buttonGroup1 = new javax.swing.ButtonGroup();
                pnlRegisterInfo = new javax.swing.JPanel();
                lblRegisterTitle = new javax.swing.JLabel();
                lblUserName = new javax.swing.JLabel();
                txtUserName = new javax.swing.JTextField();
                lblPassword = new javax.swing.JLabel();
                lblRetypePassword = new javax.swing.JLabel();
                txtPassword = new javax.swing.JPasswordField();
                btnĐangKy = new javax.swing.JButton();
                btnDangNhap = new javax.swing.JButton();
                jLabel5 = new javax.swing.JLabel();
                txtRetypePasswword = new javax.swing.JPasswordField();
                txtMaNhanVien = new javax.swing.JTextField();

                jRadioButton1.setText("jRadioButton1");

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setResizable(false);
                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowClosed(java.awt.event.WindowEvent evt) {
                                formWindowClosed(evt);
                        }
                        public void windowClosing(java.awt.event.WindowEvent evt) {
                                formWindowClosing(evt);
                        }
                });

                pnlRegisterInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));

                lblRegisterTitle.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
                lblRegisterTitle.setForeground(new java.awt.Color(255, 51, 0));
                lblRegisterTitle.setText("Tạo Tài Khoản");

                lblUserName.setText("Tên đăng nhập");

                lblPassword.setText("Mật khẩu");

                lblRetypePassword.setText("Mã Tài Khoản");

                btnĐangKy.setForeground(new java.awt.Color(255, 153, 51));
                btnĐangKy.setText("Tạo Tài Khoản Mới");
                btnĐangKy.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnĐangKyActionPerformed(evt);
                        }
                });

                btnDangNhap.setForeground(new java.awt.Color(255, 153, 51));
                btnDangNhap.setText("Đăng Nhập ");
                btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDangNhapActionPerformed(evt);
                        }
                });

                jLabel5.setText("Xác nhận mật khẩu");

                javax.swing.GroupLayout pnlRegisterInfoLayout = new javax.swing.GroupLayout(pnlRegisterInfo);
                pnlRegisterInfo.setLayout(pnlRegisterInfoLayout);
                pnlRegisterInfoLayout.setHorizontalGroup(
                        pnlRegisterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlRegisterInfoLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(pnlRegisterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlRegisterInfoLayout.createSequentialGroup()
                                                .addComponent(btnĐangKy)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(pnlRegisterInfoLayout.createSequentialGroup()
                                                .addGroup(pnlRegisterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblUserName)
                                                        .addComponent(lblPassword)
                                                        .addComponent(lblRetypePassword)
                                                        .addComponent(jLabel5))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(pnlRegisterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblRegisterTitle)
                                                        .addGroup(pnlRegisterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(txtMaNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                                .addComponent(txtRetypePasswword, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.TRAILING))
                                                        .addComponent(btnDangNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(12, Short.MAX_VALUE))))
                );
                pnlRegisterInfoLayout.setVerticalGroup(
                        pnlRegisterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlRegisterInfoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblRegisterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlRegisterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblRetypePassword)
                                        .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlRegisterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblUserName))
                                .addGap(18, 18, 18)
                                .addGroup(pnlRegisterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblPassword)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlRegisterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtRetypePasswword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(pnlRegisterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnĐangKy)
                                        .addComponent(btnDangNhap))
                                .addGap(107, 107, 107))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnlRegisterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnlRegisterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 288, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

	public static int quyen = 0;
	public static String ten = "";
    private void btnĐangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnĐangKyActionPerformed
	    String MaNhanVien, TenDangNhap, Password, NhapLai, Quyen = "";
	    MaNhanVien = txtMaNhanVien.getText().trim();
	    TenDangNhap = txtUserName.getText();
	    Password = String.valueOf(txtPassword.getPassword()).trim();
	    NhapLai = String.valueOf(txtRetypePasswword.getPassword());
	    String cautruyvan = "select *from Quyen ";
	    ResultSet rs = nhom_08.connection.ExcuteQueryGetTable(cautruyvan);
	    try {
		    while (rs.next()) {
			    if (rs.getString("TenQuyen").equals("User")) {
				    Quyen = rs.getString("MaQuyen");
			    }
		    }
	    } catch (SQLException ex) {
		    System.out.println(ex.toString());
	    }
	    if (MaNhanVien.equals("")) {
		    ThongBao("Chưa nhập mã tài khoản ", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
	    } else {
		    if (TenDangNhap.length() < 3 || TenDangNhap.length() > 10 && !KiemTraChuaChu(TenDangNhap)) {
			    ThongBao("Tên đăng nhập phải từ 3-10 ký tự", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
		    } else if (Password.length() < 6 || Password.length() > 12) {
			    ThongBao("Mật khẩu phải nhập nhiều hơn 6 ký tự và ít hơn 12 ký tự", "Lỗi đăng ký", 2);
		    } else if (!KiemTraChuaChuVaSo(Password)) {
			    ThongBao("Mật khẩu phải bao gồm chữ IN HOA, chữ thường và số", "Thông báo", 2);
		    } else if (!Password.equals(NhapLai)) {
			    ThongBao("Xác nhận mật khẩu không đúng", "Thông báo", 2);
		    } else {
			    String cautruyvan1 = "select * from Users where MaNhanVien= '" + MaNhanVien + "'";
			    ResultSet rs2 = NHOM_08.nhom_08.connection.ExcuteQueryGetTable(cautruyvan1);
			    try {
				    if (rs2.next()) {
					    ThongBao("Mã tài khoản đã tồn tại!", "Thông báo", 2);
				    } else {
					    cautruyvan = "insert into Users values(" + MaNhanVien
						    + " ,'" + TenDangNhap + "' , '" + Password + "' ," + Quyen
						    + ", N' ')";

					    nhom_08.connection.ExcuteQueryUpdateDB(cautruyvan);
					    //System.out.println(cautruyvan);
					    ThongBao("Đăng kí thành công", "Chúc mừng", 1);
				    }
			    } catch (SQLException ex) {
				    ThongBao("Không thể Thêm tài Khoản", "lỗi", 2);
			    }
		    }
	    }


    }//GEN-LAST:event_btnĐangKyActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
//
//        String strUsername = txtUserName.getText().trim();
//        String strPassword = String.valueOf(txtPassword.getPassword()).trim();
//        if (strUsername.equals("")) {
//            ThongBao("Bạn Chưa Nhập: Tên Đăng Nhập", "Lỗi đăng nhập", 2);
//        } else if (strPassword.equals("")) {
//            ThongBao("Bạn Chưa Nhập: Mật Khẩu", "Lỗi đăng nhập", 2);
//        } else if (KiemTra(strUsername, strPassword)) {
//            DangNhap dangNhap = new DangNhap();
//            dangNhap.show();
//            this.dispose();
//        } else {
//            ThongBao("Bạn nhập sai tài khoản hoặc mật khẩu", "Lỗi đăng nhập", 2);
//        }
	    DangNhap dangNhap = new DangNhap();
	    dangNhap.show();
	    this.dispose();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
	    DangNhap frmDN = new DangNhap();
	    frmDN.show();
	    this.dispose();
    }//GEN-LAST:event_formWindowClosing

	private boolean KiemTra(String tdn, String mk) {
		boolean kq = false;

		String cautruyvan = "select * from Users where TenDangNhap= '" + tdn + "' and Password= '" + mk + "'";
		System.out.println(cautruyvan);
		ResultSet rs = NHOM_08.nhom_08.connection.ExcuteQueryGetTable(cautruyvan);

		try {
			if (rs.next()) {
				kq = true;
				quyen = rs.getInt("Quyen");
				ten = rs.getString("TenDangNhap");
				System.out.println(" " + quyen);
			}
		} catch (SQLException ex) {
			System.out.println("lỗi đăng nhập");
		}

		return kq;
	}

	private boolean KiemTraChuaChuVaSo(String chuoi) {
		boolean ketqua = false;
		Pattern p = Pattern.compile("[a-zA-Z][0-9]");
		Matcher m = p.matcher(chuoi);
		if (!(chuoi == chuoi.toLowerCase())) {
			ketqua = m.find();
		}
		return ketqua;
	}

	private boolean KiemTraChuaChu(String chuoi) {
		boolean ketqua = false;
		Pattern p = Pattern.compile("[a-zA-Z]");
		Matcher m = p.matcher(chuoi);
		if (!(chuoi == chuoi.toLowerCase())) {
			ketqua = m.find();
		}
		return ketqua;
	}

	public boolean KiemTraEmail(String email) {
		boolean kq = false;
		String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
		Pattern v = Pattern.compile(EMAIL_PATTERN);
		Matcher m = v.matcher(email);
		kq = m.matches();
		return kq;
	}

	private void ThongBao(String noiDungThongBao, String tieuDeThongBao, int icon) {
		JOptionPane.showMessageDialog(new JFrame(), noiDungThongBao,
			tieuDeThongBao, icon);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DangKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DangKy().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnDangNhap;
        private javax.swing.JButton btnĐangKy;
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JRadioButton jRadioButton1;
        private javax.swing.JLabel lblPassword;
        private javax.swing.JLabel lblRegisterTitle;
        private javax.swing.JLabel lblRetypePassword;
        private javax.swing.JLabel lblUserName;
        private javax.swing.JPanel pnlRegisterInfo;
        private javax.swing.JTextField txtMaNhanVien;
        private javax.swing.JPasswordField txtPassword;
        private javax.swing.JPasswordField txtRetypePasswword;
        private javax.swing.JTextField txtUserName;
        // End of variables declaration//GEN-END:variables
}
